### ISSUE TITLE
Giving wrong code for my unit

### ISSUE THREAD

**Issue by alanorth** [Berks/python_erc#1]
This is awesome! Great project. FYI this is giving the wrong ERC code for my 2015 Toyota Rav4, while https://github.com/alexeyfadeev/erc-calculator is working (more of a pain to build though!). I'm decent at Python, but bad at bitwise operations (as you alluded to in your comment in `main.py`. If I find time I'll try to look at the code and understand it... super annoying that there are all these scammy websites charging money for this stuff.

**Comment by Berks** [comment]
If you don't mind, could you share your code? I only had two to test when initially writing. I would have to take a look back at what might be going wrong.

**Comment by alanorth** [comment]
Sure. Here is the info:

- Serial: 0C44050000000000
- python_erc: -0X1BD0511
- erc-calculator: FE42FAEF

**Comment by Berks** [comment]
I updated the master with a fix that should resolve this issue. Let me know if you find any others.
